function horror(){
    document.getElementById("textarea").innerHTML = "At Saturday,September 24th, 1994 there was a man named Sam and he was 35 years old not married. Sam was on the streets walking looking for a restaurant because every Saturday he would eat dinner from a restaurant. Sam would always try to go to different restaurants every Saturday but if he is chooses to  be lazy, then he would go to his favourite restaurant, Nicely a fancy restaurant, and this was one of those Saturday's but, today, was, horrifying. When Sam walked in there was no one which is nearly impossible every day the restaurant would be full of people no matter what. Sam was a little confused. suddenly the entrance door closed *door slams* Sam was now a little scared he tried to open the door but it was locked. Now Sam was really scared that he started shivering, but lucky Sam would always bring a gun for self defence so then Sam said come out i am not afaird of you but then the door automatically opened and Sam fell down then he ran to the nearest police station. Note: not real.";
   ss = document.getElementById("textarea").innerHTML = "At Saturday,September 24th, 1994 there was a man named Sam and he was 35 years old not married. Sam was on the streets walking looking for a restaurant because every Saturday he would eat dinner from a restaurant. Sam would always try to go to different restaurants every Saturday but if he is chooses to  be lazy, then he would go to his favourite restaurant, Nicely a fancy restaurant, and this was one of those Saturday's but, today, was, horrifying. When Sam walked in there was no one which is nearly impossible every day the restaurant would be full of people no matter what. Sam was a little confused. suddenly the entrance door closed *door slams* Sam was now a little scared he tried to open the door but it was locked. Now Sam was really scared that he started shivering, but lucky Sam would always bring a gun for self defence so then Sam said come out i am not afaird of you but then the door automatically opened and Sam fell down then he ran to the nearest police station. Note: not real.";
}

function magical(){
    document.getElementById("textarea").innerHTML = "At Tuesday,December 25th or at chrismas,1990 there was a 6 years old boy named Leo that believed santa existed so at every chrismas he would stay awake all night thinking santa will come. but every chrismas he would be disapointed because santa didn't come so next chrismas he left blieving santa exist's but that chrismas day he randomly woke up at the middle of the night and he heard footsteps so Leo went down running and then he saw! no one again Leo was disapointed but when he turns back! There's santa! Leo was so uncontrollably happy and Leo said I knew you existed santa I knew santa said hohoho you were so right! then santa said I am sorry but I have to give other children gifts but Leo was not disapointed this time he said please come back and meet me please! and santa said I will always try my best to meet you every chrismas hohohohoho and then he vanished then he started going on his reindeer cart laughing hohohooo. Note: not real ";
}

function happy(){
    document.getElementById("textarea").innerHTML = "At Friday,September 8th, 2023 there was a 10 years old boy named Abubaqr he went to America and in America he went to Florida then the next day Saturday, September 9th, 2023 he went to Disney World and spent more than 7 hours there, it was really fun he saw two ceremonies entrance ceremony, and another ceremony but he forgot the name. Then after the entrance ceremony he went to fun rides with his friend Shayaan and his family then at the end he went to a restaurant and it was delicious. Note: real"
}

function inter(){
    document.getElementById("textarea").innerHTML = "At Monday,October 5th, 2015 there was a 30 years old woman named lily she was a detective that day there was a report of a crime and the crime was a stealing someone stole a very expensive ring from a jewelry shop and it was her job to figure it out. so she went to the jewerly shop and looked and she found out that actually not one or two but five jewerlies so she looked where the jewerly places and found 6 fingerprints? so then it was confusing 5 stolen but 6 found. but o'well she had to give what she had. Then after a few days the police found and caught the suspects but none of the jewerlies were there. and all 6 people were found now she had to figure out where jewerlies were while the police were talking to the suspects. now she looked for hours and hours until she found a box! but it was locker box so then she thought there has to be code somewhere around and she looked around for hours and hours until she gave up but while she was going out of the place she found a code 567890 she put the code and the box opened! and all five jewrelies were there and the police found out all 6 suspects were involved in the crime but one couldn't get a jewrely but he tried to."
}

function save(){
    ss = document.getElementById("textarea").value;
    localStorage.setItem("textarea", ss)
    document.getElementById("textarea").innerHTML = ss;
}